# netlify.toml - Configuration file for Netlify

[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000

# Environment variables are better set in the Netlify UI
# But you can define defaults here

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200