[build]
  publish = "public"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/"
  to = "/.netlify/functions/serve"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/.netlify/functions/dashboard"
  status = 200

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
